#!/bin/bash
# Get the lattices from Kaldi for each dataset that has been decoded
# dev, dev2 and test : Fisher
# Acoustic scale set to 1/W, where W led to the best WER
# --- The symbols for laugh, noise and OOV , <unk> are hardcoded in the Kaldi2FST script. You should replace them (2035, 2038, 2039, 2040 in the default recipe)
# since they get replaced with eplison upon conversion
# --- Pruned with a beam width of 13.0
asr_util/kaldi2FST.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/dev/lattices \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev 0.067

asr_util/kaldi2FST.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/dev2/lattices \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev2 0.067

asr_util/kaldi2FST.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/test/lattices \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_test 0.067

# (OPTIONAL)
# Merge lattices based on timing information available
# Convert to PLF
asr_util/mainPLF.py -l data/asr/dev/lattices/lattices-pushed \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev -o data/asr/dev/plf \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim
asr_util/mainPLF.py -l data/asr/test/lattices/lattices-pushed \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/test \
  -o data/asr/test/plf \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim

# Get nbest files
nohup asr_util/kaldi2NBest.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/dev/nbest \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev \
  0.067 \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt > log/nbest_dev.out &

nohup asr_util/kaldi2NBest.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/dev2/nbest \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev2 \
  0.067 \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt > log/nbest_dev2.out &

nohup asr_util/kaldi2NBest.sh \
  /export/a04/gkumar/code/kaldi-new \
  data/asr/test/nbest \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_test \
  0.067 \
  /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt > log/nbest_test.out &

# Merge 1best files based on timing information
nohup asr_util/merge1Best.py \
  -i /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev/scoring/15.tra \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev \
  -o data/asr/dev/1best \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/dev.1best.out &

nohup asr_util/merge1Best.py \
  -i /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_dev2/scoring/15.tra \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev2 \
  -o data/asr/dev2/1best \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/dev2.1best.out &

nohup asr_util/merge1Best.py \
  -i /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri6a_dnn/decode_test/scoring/15.tra \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/test \
  -o data/asr/test/1best \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/test.1best.out &

# Get the nbest files based on timing information
# awk '{s+=$1} END {print s}' asr.ncount
# to verify if the counts match the nbest hyps
nohup asr_util/mergeNBest.py \
  -i data/asr/dev/nbest/all.nbest \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev \
  -o data/asr/dev/nbest \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/dev.nbest.merge.out &
nohup asr_util/mergeNBest.py \
  -i data/asr/dev2/nbest/all.nbest \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev2 \
  -o data/asr/dev2/nbest \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/dev2.nbest.merge.out &
nohup asr_util/mergeNBest.py \
  -i data/asr/test/nbest/all.nbest \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/test \
  -o data/asr/test/nbest \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim > log/test.nbest.merge.out &

# Clean the 1-best files
asr_util/cleanASROutput.sh data/asr/dev/1best/asr.1best
asr_util/cleanASROutput.sh data/asr/dev2/1best/asr.1best
asr_util/cleanASROutput.sh data/asr/test/1best/asr.1best

# Clean the n-best files
asr_util/cleanASROutput.sh data/asr/dev/nbest/asr.nbest
asr_util/cleanASROutput.sh data/asr/dev2/nbest/asr.nbest
asr_util/cleanASROutput.sh data/asr/test/nbest/asr.nbest

# Generate reference for the n-best files
asr_util/replicateReference.py -c data/asr/dev/nbest/asr.ncount -r data/asr/dev/ref/fisher_dev.tok.lc.en.0 -o data/asr/dev/nbest/nbest.en.0
asr_util/replicateReference.py -c data/asr/dev/nbest/asr.ncount -r data/asr/dev/ref/fisher_dev.tok.lc.en.1 -o data/asr/dev/nbest/nbest.en.1
asr_util/replicateReference.py -c data/asr/dev/nbest/asr.ncount -r data/asr/dev/ref/fisher_dev.tok.lc.en.2 -o data/asr/dev/nbest/nbest.en.2
asr_util/replicateReference.py -c data/asr/dev/nbest/asr.ncount -r data/asr/dev/ref/fisher_dev.tok.lc.en.3 -o data/asr/dev/nbest/nbest.en.3
asr_util/replicateReference.py -c data/asr/dev2/nbest/asr.ncount -r data/asr/dev2/ref/fisher_dev2.tok.lc.en.0 -o data/asr/dev2/nbest/nbest.en.0
asr_util/replicateReference.py -c data/asr/dev2/nbest/asr.ncount -r data/asr/dev2/ref/fisher_dev2.tok.lc.en.1 -o data/asr/dev2/nbest/nbest.en.1
asr_util/replicateReference.py -c data/asr/dev2/nbest/asr.ncount -r data/asr/dev2/ref/fisher_dev2.tok.lc.en.2 -o data/asr/dev2/nbest/nbest.en.2
asr_util/replicateReference.py -c data/asr/dev2/nbest/asr.ncount -r data/asr/dev2/ref/fisher_dev2.tok.lc.en.3 -o data/asr/dev2/nbest/nbest.en.3
asr_util/replicateReference.py -c data/asr/test/nbest/asr.ncount -r data/asr/test/ref/fisher_test.tok.lc.en.0 -o data/asr/test/nbest/nbest.en.0
asr_util/replicateReference.py -c data/asr/test/nbest/asr.ncount -r data/asr/test/ref/fisher_test.tok.lc.en.1 -o data/asr/test/nbest/nbest.en.1
asr_util/replicateReference.py -c data/asr/test/nbest/asr.ncount -r data/asr/test/ref/fisher_test.tok.lc.en.2 -o data/asr/test/nbest/nbest.en.2
asr_util/replicateReference.py -c data/asr/test/nbest/asr.ncount -r data/asr/test/ref/fisher_test.tok.lc.en.3 -o data/asr/test/nbest/nbest.en.3

# Merge lattices
asr_util/mergeLattices.py -l data/asr/dev/lattices/lattices-pushed \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev -o data/asr/dev/mergedLat \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim
asr_util/mergeLattices.py -l data/asr/dev2/lattices/lattices-pushed \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/dev2 -o data/asr/dev2/mergedLat \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim
asr_util/mergeLattices.py -l data/asr/test/lattices/lattices-pushed \
  -s /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -c /export/a04/gkumar/corpora/fishcall/jack-splits/split-matt/test -o data/asr/test/mergedLat \
  -t /export/a04/gkumar/corpora/fishcall/fisher/tim

# Remove weights from lattices (needed for some experiments)
asr_util/removeLatWeights.sh data/asr/dev/mergedLat/finalLat data/asr/dev/mergedLat/noWeightLat
asr_util/removeLatWeights.sh data/asr/dev2/mergedLat/finalLat data/asr/dev2/mergedLat/noWeightLat
asr_util/removeLatWeights.sh data/asr/test/mergedLat/finalLat data/asr/test/mergedLat/noWeightLat

###############
# MT Steps
###############

# Decode n-best list
nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/8 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/data/asr/dev/nbest/asr.nbest.clean \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.nbest.dev.out &

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/6 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/data/asr/dev2/nbest/asr.nbest.clean \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.nbest.dev2.out &

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/7 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/data/asr/test/nbest/asr.nbest.clean \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.nbest.test.out &

# Create a phrase table that does not use smoothing

# Extract features from the phrase table, use filtered phrase tables
time mt_util/extractPhraseFeats.py -p /export/a04/gkumar/experiments/is2015/8/evaluation/test.filtered.1/phrase-table.0-0.1.1.gz -o data/mt/phrase_feats.dev
time mt_util/extractPhraseFeats.py -p /export/a04/gkumar/experiments/is2015/6/evaluation/test.filtered.1/phrase-table.0-0.1.1.gz -o data/mt/phrase_feats.dev2
time mt_util/extractPhraseFeats.py -p /export/a04/gkumar/experiments/is2015/7/evaluation/test.filtered.1/phrase-table.0-0.1.1.gz -o data/mt/phrase_feats.test
#time mt_util/extractPhraseFeats.py -p /export/a04/gkumar/experiments/is2015/4/model/phrase-table.ns.1.gz -o data/mt/phrase_feats

# Create the feat file to an FST, requires a weight file
time mt_util/phrase2FST.py \
  -p data/mt/phrase_feats.dev \
  -f exp/1_dev/S.dev.fst.txt \
  -s exp/1_dev/syms.dev.txt \
  -e /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -w exp/1_dev/weights.init
time mt_util/phrase2FST.py \
  -p data/mt/phrase_feats.dev \
  -f exp/1_dev2/S.dev2.fst.txt \
  -s exp/1_dev2/syms.dev2.txt \
  -e /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -w exp/1_dev2/weights.init
time mt_util/phrase2FST.py \
  -p data/mt/phrase_feats.dev \
  -f exp/1_test/S.test.fst.txt \
  -s exp/1_test/syms.test.txt \
  -e /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  -w exp/1_test/weights.init

# Compile the segmentation transducer
fstcompile --arc_type=log S.dev.fst.txt S.dev.fst
fstcompile --arc_type=log S.dev2.fst.txt S.dev2.fst
fstcompile --arc_type=log S.test.fst.txt S.test.fst

############ LENGTH BASED FEATURES #################
# Create phrase lattices
nohup mt_util/createPhraseLattice.sh data/asr/dev/mergedLat/noWeightLat/ \
  exp/1_dev/S.dev.fst /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  exp/1_dev/res > log/pl.dev.log &

nohup mt_util/createPhraseLattice.sh data/asr/dev2/mergedLat/noWeightLat/ \
  exp/1_dev2/S.dev2.fst /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  exp/1_dev2/res > log/pl.dev2.log &

nohup mt_util/createPhraseLattice.sh data/asr/test/mergedLat/noWeightLat/ \
  exp/1_test/S.test.fst /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  exp/1_test/res > log/pl.test.log &

# Extract the 1-best lat files 
mt_util/get1Best.py -i exp/1_dev/res/1best -a data/asr/dev/1best/asr.1best.clean -o exp/1_dev/res/1best/dev.lat.1best
mt_util/get1Best.py -i exp/1_dev2/res/1best -a data/asr/dev2/1best/asr.1best.clean -o exp/1_dev2/res/1best/dev2.lat.1best
mt_util/get1Best.py -i exp/1_test/res/1best -a data/asr/test/1best/asr.1best.clean -o exp/1_test/res/1best/test.lat.1best

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/13 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/exp/1_dev2/res/1best/dev2.lat.1best \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.l.1.1best.dev2.out &

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/14 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/exp/1_test/res/1best/test.lat.1best \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.l.1.1best.test.out &

############ ASR DRAWS #################
# Create phrase lattices

nohup mt_util/asrDrawsMain.sh data/asr/dev2/mergedLat/noWeightLat/ data/asr/dev2/mergedLat/finalLat \
  exp/1_dev/S.fst /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  exp/2_dev2/res > log/p.dev2.2.log &

nohup mt_util/asrDrawsMain.sh data/asr/test/mergedLat/noWeightLat/ data/asr/test/mergedLat/finalLat \
  exp/1_dev/S.fst /export/a04/gkumar/code/kaldi-new/egs/fisher_callhome_spanish/s5/exp/tri5a/graph/words.txt \
  exp/2_test/res > log/p.test.2.log &

# Extract the 1-best lat files 
mt_util/get1Best.py -i exp/2_dev2/res/1best -a data/asr/dev2/1best/asr.1best.clean -o exp/2_dev2/res/1best/dev2.lat.1best
mt_util/get1Best.py -i exp/2_test/res/1best -a data/asr/test/1best/asr.1best.clean -o exp/2_test/res/1best/test.lat.1best

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/11 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/exp/2_dev2/res/1best/dev2.lat.1best \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.l.2.1best.dev2.out &

nohup mt_util/mosesFilterDecode.sh /export/a04/gkumar/experiments/is2015/12 \
  /export/a04/gkumar/code/custom/phrase_speech_translation/exp/2_test/res/1best/test.lat.1best \
  /export/a04/gkumar/experiments/is2015/5/tuning/moses.tuned.ini.1 \
  /export/a04/gkumar/experiments/is2015/5/model > log/decode.l.2.1best.test.out &
##############
# Interface steps
# ############
# To get sentence level BLEU
/export/a04/gkumar/code/mosesdecoder/bin/sentence-bleu refs... < cand

