#!/bin/bash

# Usage: fstprintstring [in.fst] [symtable] [n]
# Derived from Jason Eisner's implementation (http://www.cs.jhu.edu/~jason/465/hw-ofst/bin/fstprintstring)
#
# Prints a random output string from the FST.

syms=$2

fstshortestpath $1 | \
  fstproject --project_output=true | \
  fstrmepsilon | fsttopsort | fstprint --isymbols=$syms --osymbols=$syms | cut -sf4 | \
  perl -0777 -pe 's/^0x20$/ /mg; if (/[^\n][^\n]/) { s/\n/ /g } else { s/\n//g } $_.="\n"'
  # perl script changes 0x20 to space, then turns newlines into spaces if any symbols have length > 1, and else deletes them.
