/*

fstprintpaths.hpp

traverses an fst and prints out all of the paths in that fst along with the costs.

output format is: WORD cost X.XX

where WORD is a sequence of characters accepted or generated by the fst AND X.XX 
is a floating point value representing the cost of traversing that structure.

author: chris taylor

OpenFst forum post title: "Natural code for printing all strings accepted by an FST?"
OpenFst forum post link: http://openfst.cs.nyu.edu/twiki/bin/view/Forum/FstForum#Natural_code_for_printing_all_st

author: Gaurav Kumar 

Changed to print paths using a vector : Can take care of multiple paths in a DFS manner
Added cli options to print input output or both

*/

#ifndef __FSTPRINTPATH__
#define __FSTPRINTPATH__

#include <vector>
#include <iostream>
#include<string>
#include<sstream>

#include "fst/fst.h"
#include "fst/compact-fst.h"
#include "fst/vector-fst.h"
#include "fst/float-weight.h" 

#include "utils.hpp"

using namespace std;
using namespace fst;

namespace openfsttools 
{

class fstprintpaths
{
    public:

    enum ProjectionEnum { PROJECT_INPUT, PROJECT_OUTPUT, PROJECT_BOTH } ;

    static void printAllStrings(StdVectorFst& fst, SymbolTable& st, string& seqToSkip, int mode);

    static void printAllStringsHelper(StdVectorFst& fst, SymbolTable& st, int state, vector<string>& strVecInput, vector<string>& strVecOutput, TropicalWeight cost, string& seqToSkip, ProjectionEnum printInputOrOutput=PROJECT_OUTPUT); 

}; // end class

} // end namespace 

#endif

